
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

const SUPABASE_URL = "https://nkxpegofbplfxxyvjhhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5reHBlZ29mYnBsZnh4eXZqaGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjUzOTksImV4cCI6MjA1ODUwMTM5OX0.Gnq0ydBg3SELwo0HdqKf7mvEFi3AuStcDPFfX39ucuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
